version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: annotation_tool
    ports:
      - "8070:8070"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    restart: unless-stopped